name: CI/CD Pipeline

on: 
  push:
    branches:
        [ main ]

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout do código
              uses: actions/checkout@v3

            - name: Login no Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Build e push da imagem Docker
              uses: docker/build-push-action@v5
              with:
                context: .
                push: true
                tags: ${{ secrets.DOCKER_USERNAME }}/hello-app:${{ github.run_number }}

            - name: Configurar acesso SSH para o repositório de manifests
              uses: webfactory/ssh-agent@v0.7.0
              with:
                ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
            
            - name: Clonar repositório de manifests
              run: |
                git clone git@github.com:Luisdevux/hello-manifests.git manifests-repo
            
            - name: Atualizar imagem no deployment manifest
              run: |
                sed -i "s|^\s*image: .*|image: ${{ secrets.DOCKER_USERNAME }}/hello-app:${{ github.run_number }}|g" manifests-repo/k8s/deployment.yaml
                cd manifests-repo
                git config --global user.name "github-actions"
                git config --global user.email "actions@github.com"
                git add k8s/deployment.yaml
                git commit -m "Atualiza imagem para tag ${{ github.run_number }}" || echo "Nenhuma mudança para commitar"
                git push origin main

            - name: Configurar kubectl
              run: |
                echo "${{ secrets.KUBE_CONFIG_DATA }}" | base64 --decode > $HOME/.kube/config

            - name: Aplicar deployment no Kubernetes
              run: |
                kubectl apply -f manifests-repo/k8s/deployment.yaml